### ISSUE TITLE
Itinerary view: tourstop box

### ISSUE THREAD

**Issue by suhbr** [SatabdiG/TripAroundSeller#18]
"Durchsuchen" button doesn't fit in the message box of the tour stops.
"Durchsuchen" button enlarges when picture is selected --> shows name of picture and doesn't disappear.
Edited text is below/over name of chosen picture.
Edited text disappears when another picture is uploaded and "save" is clicked.

![grafik](https://cloud.githubusercontent.com/assets/19994919/21015663/296faba8-bd63-11e6-9364-c2024383803f.png)

**Comment by SatabdiG** [comment]
Done
